name: Android CI7

on: 
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK              
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
    
      - name: Change wrapper permissions 
        run: chmod +x ./gradlew

      - name: Run Tests                   
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew build

      - name: Pack Project               
        run: ./gradlew assemble         
        
      - name: LS
        run: ls -la ./build/

        # Noted For Output [main_project_module]/build/
      - name: Upload Build 
        uses: actions/upload-artifact@v4
        with:
          name: Files generated
          path: ./build/
