name: Android CI

on: 
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK              // 1
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Change wrapper permissions  // 2
        run: chmod +x ./gradlew

      - name: Run Tests                   // 3
        run: ./gradlew test

      - name: Build Project               // 4
        run: ./gradlew assemble         ./gradlew build

     
        # Noted For Output [main_project_module]/build/outputs/apk/release/
      - name: Upload APK Release 
        uses: actions/upload-artifact@v4
        with:
          name: APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/
